# Generated by Django 5.2.7 on 2025-11-24 07:11

from django.db import migrations, models
from django.utils.text import slugify


def _generate_unique_slug(title, existing):
    base = slugify(title)
    slug = base
    i = 1
    while slug in existing:
        slug = f"{base}-{i}"
        i += 1
    existing.add(slug)
    return slug


def populate_slugs(apps, schema_editor):
    Post = apps.get_model('games', 'Post')
    existing = set()
    for p in Post.objects.all():
        if getattr(p, 'slug', None):
            existing.add(p.slug)
    for p in Post.objects.all():
        if not getattr(p, 'slug', None):
            p.slug = _generate_unique_slug(p.title, existing)
            p.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
