# Generated by Django 5.2.7 on 2025-11-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
